name: Generate Dashboards

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4

      - name: Install pandas
        run: pip install pandas

      - name: Run script
        run: python generate_dashboards.py
